const INCREASEMENT = 'INCREASEMENT'
const DECREASEMENT= 'DECREASEMENT'
const DIALOG = 'DIALOG'
const CHENGDENG = 'CHENGDENG'
const CHUDENG = 'CHUFENG'

export default {
	INCREASEMENT,
	DECREASEMENT,
	DIALOG,
	CHENGDENG,
	CHUDENG
}
